const configuration = [
    {
        title: "Широкоформатная сольвентная печать",
        options: [
            {
                value: "1",
                material: "Баннер",
                density: "440",
                type: "ламинированный",
                quality: "360",
                color: "",
                prices: {
                    upTo1: "370",
                    upTo5: "360",
                    upTo20: "270",
                    upTo100: "245",
                    over100: "230",
                },
            },
            {
                value: "2",
                material: "Баннер",
                density: "440",
                type: "ламинированный",
                quality: "540",
                color: "",
                prices: {
                    upTo1: "440",
                    upTo5: "435",
                    upTo20: "350",
                    upTo100: "330",
                    over100: "320",
                },
            },
            {
                value: "3",
                material: "Баннер",
                density: "440",
                type: "литой",
                quality: "360",
                color: "",
                prices: {
                    upTo1: "480",
                    upTo5: "470",
                    upTo20: "380",
                    upTo100: "355",
                    over100: "340",
                },
            },
            {
                value: "4",
                material: "Баннер",
                density: "440",
                type: "литой",
                quality: "540",
                color: "",
                prices: {
                    upTo1: "550",
                    upTo5: "545",
                    upTo20: "460",
                    upTo100: "440",
                    over100: "430",
                },
            },
            {
                value: "5",
                material: "Баннер",
                density: "510",
                type: "литой",
                quality: "360",
                color: "",
                prices: {
                    upTo1: "610",
                    upTo5: "600",
                    upTo20: "510",
                    upTo100: "485",
                    over100: "470",
                },
            },
            {
                value: "6",
                material: "Баннер",
                density: "510",
                type: "литой",
                quality: "540",
                color: "",
                prices: {
                    upTo1: "680",
                    upTo5: "675",
                    upTo20: "590",
                    upTo100: "570",
                    over100: "560",
                },
            },
            {
                value: "7",
                material: "Баннерная сетка",
                density: "",
                type: "",
                quality: "360",
                color: "",
                prices: {
                    upTo1: "520",
                    upTo5: "505",
                    upTo20: "415",
                    upTo100: "380",
                    over100: "360",
                },
            },
            {
                value: "8",
                material: "Пленка",
                density: "",
                type: "самоклеящаяся",
                quality: "360",
                color: "",
                prices: {
                    upTo1: "410",
                    upTo5: "400",
                    upTo20: "310",
                    upTo100: "285",
                    over100: "270",
                },
            },
            {
                value: "9",
                material: "Пленка",
                density: "",
                type: "самоклеящаяся",
                quality: "540",
                color: "",
                prices: {
                    upTo1: "480",
                    upTo5: "445",
                    upTo20: "390",
                    upTo100: "370",
                    over100: "360",
                },
            },
            {
                value: "10",
                material: "Пленка",
                density: "",
                type: "перфорированная",
                quality: "360",
                color: "",
                prices: {
                    upTo1: "590",
                    upTo5: "575",
                    upTo20: "480",
                    upTo100: "445",
                    over100: "420",
                },
            },
        ],
    },
    {
        title: "Интерьерная экосольвентная печать",
        options: [
            {
                value: "1",
                material: "Баннер",
                density: "440",
                type: "ламинированный",
                quality: "720",
                color: "",
                prices: {
                    upTo1: "520",
                    upTo5: "510",
                    upTo20: "420",
                    upTo100: "395",
                    over100: "380",
                },
            },
            {
                value: "2",
                material: "Баннер",
                density: "",
                type: "для роллерных стендов",
                quality: "720",
                color: "",
                prices: {
                    upTo1: "730",
                    upTo5: "720",
                    upTo20: "630",
                    upTo100: "605",
                    over100: "590",
                },
            },
            {
                value: "3",
                material: "Бумага",
                density: "150",
                type: "постерная",
                quality: "720",
                color: "",
                prices: {
                    upTo1: "340",
                    upTo5: "335",
                    upTo20: "245",
                    upTo100: "225",
                    over100: "210",
                },
            },
            {
                value: "4",
                material: "Фотобумага",
                density: "220",
                type: "",
                quality: "720",
                color: "",
                prices: {
                    upTo1: "690",
                    upTo5: "670",
                    upTo20: "560",
                    upTo100: "515",
                    over100: "480",
                },
            },
            {
                value: "5",
                material: "Фотобумага",
                density: "220",
                type: "",
                quality: "1440",
                color: "",
                prices: {
                    upTo1: "890",
                    upTo5: "870",
                    upTo20: "760",
                    upTo100: "715",
                    over100: "680",
                },
            },
            {
                value: "6",
                material: "Пленка",
                density: "",
                type: "самоклеящаяся",
                quality: "720",
                color: "белая",
                prices: {
                    upTo1: "520",
                    upTo5: "510",
                    upTo20: "420",
                    upTo100: "395",
                    over100: "380",
                },
            },
            {
                value: "7",
                material: "Пленка",
                density: "",
                type: "самоклеящаяся",
                quality: "1440",
                color: "белая",
                prices: {
                    upTo1: "600",
                    upTo5: "595",
                    upTo20: "510",
                    upTo100: "485",
                    over100: "440",
                },
            },
            {
                value: "8",
                material: "Пленка",
                density: "",
                type: "самоклеящаяся",
                quality: "720",
                color: "прозрачная",
                prices: {
                    upTo1: "520",
                    upTo5: "510",
                    upTo20: "420",
                    upTo100: "395",
                    over100: "380",
                },
            },
            {
                value: "9",
                material: "Пленка",
                density: "",
                type: "самоклеящаяся",
                quality: "1440",
                color: "прозрачная",
                prices: {
                    upTo1: "600",
                    upTo5: "595",
                    upTo20: "510",
                    upTo100: "485",
                    over100: "440",
                },
            },
            {
                value: "10",
                material: "Пленка",
                density: "",
                type: "светоотражающая",
                quality: "1440",
                color: "",
                prices: {
                    upTo1: "1320",
                    upTo5: "1315",
                    upTo20: "1230",
                    upTo100: "1205",
                    over100: "1190",
                },
            },
            {
                value: "11",
                material: "Холст",
                density: "",
                type: "",
                quality: "1440",
                color: "",
                prices: {
                    upTo1: "1720",
                    upTo5: "1630",
                    upTo20: "1450",
                    upTo100: "1335",
                    over100: "1180",
                },
            },
        ],
    },
    {
        title: "Рулонная УФ-печать",
        options: [
            {
                value: "1",
                material: "Баннер",
                density: "440",
                type: "ламинированный",
                quality: "360",
                color: "",
                prices: {
                    upTo1: "760",
                    upTo5: "730",
                    upTo20: "630",
                    upTo100: "565",
                    over100: "510",
                },
            },
            {
                value: "2",
                material: "Баннер",
                density: "440",
                type: "ламинированный",
                quality: "720",
                color: "",
                prices: {
                    upTo1: "910",
                    upTo5: "860",
                    upTo20: "730",
                    upTo100: "635",
                    over100: "560",
                },
            },
            {
                value: "3",
                material: "Бумага",
                density: "150",
                type: "постерная",
                quality: "720",
                color: "",
                prices: {
                    upTo1: "850",
                    upTo5: "840",
                    upTo20: "570",
                    upTo100: "575",
                    over100: "500",
                },
            },
            {
                value: "4",
                material: "Фотобумага",
                density: "220",
                type: "",
                quality: "720",
                color: "",
                prices: {
                    upTo1: "960",
                    upTo5: "910",
                    upTo20: "780",
                    upTo100: "685",
                    over100: "610",
                },
            },
            {
                value: "5",
                material: "Фотобумага",
                density: "220",
                type: "",
                quality: "1200",
                color: "",
                prices: {
                    upTo1: "1060",
                    upTo5: "1030",
                    upTo20: "930",
                    upTo100: "865",
                    over100: "810",
                },
            },
            {
                value: "6",
                material: "Пленка",
                density: "",
                type: "самоклеящаяся",
                quality: "360",
                color: "белая",
                prices: {
                    upTo1: "800",
                    upTo5: "770",
                    upTo20: "670",
                    upTo100: "605",
                    over100: "550",
                },
            },
            {
                value: "7",
                material: "Пленка",
                density: "",
                type: "самоклеящаяся",
                quality: "720",
                color: "белая",
                prices: {
                    upTo1: "950",
                    upTo5: "900",
                    upTo20: "770",
                    upTo100: "675",
                    over100: "600",
                },
            },
            {
                value: "8",
                material: "Пленка",
                density: "",
                type: "самоклеящаяся",
                quality: "1200",
                color: "белая",
                prices: {
                    upTo1: "1050",
                    upTo5: "1020",
                    upTo20: "720",
                    upTo100: "670",
                    over100: "620",
                },
            },
            {
                value: "9",
                material: "Пленка",
                density: "",
                type: "самоклеящаяся",
                quality: "360",
                color: "прозрачная",
                prices: {
                    upTo1: "800",
                    upTo5: "770",
                    upTo20: "670",
                    upTo100: "605",
                    over100: "550",
                },
            },
            {
                value: "10",
                material: "Пленка",
                density: "",
                type: "самоклеящаяся",
                quality: "720",
                color: "прозрачная",
                prices: {
                    upTo1: "950",
                    upTo5: "900",
                    upTo20: "770",
                    upTo100: "675",
                    over100: "600",
                },
            },
            {
                value: "11",
                material: "Пленка",
                density: "",
                type: "самоклеящаяся",
                quality: "1200",
                color: "прозрачная",
                prices: {
                    upTo1: "1050",
                    upTo5: "1020",
                    upTo20: "720",
                    upTo100: "670",
                    over100: "620",
                },
            },
            {
                value: "12",
                material: "Пленка",
                density: "",
                type: "светонакапливающая",
                quality: "720",
                color: "",
                prices: {
                    upTo1: "4870",
                    upTo5: "4820",
                    upTo20: "4690",
                    upTo100: "4595",
                    over100: "4520",
                },
            },
            {
                value: "13",
                material: "Холст",
                density: "",
                type: "",
                quality: "1200",
                color: "",
                prices: {
                    upTo1: "1200",
                    upTo5: "1170",
                    upTo20: "1070",
                    upTo100: "1005",
                    over100: "950",
                },
            },
        ],
    },
    {
        title: "Планшетная УФ-печать",
        options: [
            {
                value: "1",
                material: "ПВХ 3мм",
                density: "",
                type: "",
                quality: "",
                color: "",
                prices: {
                    upTo1: "2500",
                    upTo5: "2400",
                    upTo20: "2170",
                    upTo100: "1905",
                    over100: "1800",
                },
            },
            {
                value: "2",
                material: "ПЭТ 1мм",
                density: "",
                type: "",
                quality: "",
                color: "",
                prices: {
                    upTo1: "2300",
                    upTo5: "2200",
                    upTo20: "1970",
                    upTo100: "1705",
                    over100: "1600",
                },
            },
            {
                value: "3",
                material: "Акрил 3мм",
                density: "",
                type: "",
                quality: "",
                color: "",
                prices: {
                    upTo1: "5600",
                    upTo5: "5500",
                    upTo20: "5270",
                    upTo100: "5000",
                    over100: "4900",
                },
            },
            {
                value: "4",
                material: "Двухслойный пластик",
                density: "",
                type: "",
                quality: "",
                color: "",
                prices: {
                    upTo1: "5400",
                    upTo5: "5300",
                    upTo20: "5070",
                    upTo100: "4800",
                    over100: "4700",
                },
            },
            {
                value: "5",
                material: "Пленка",
                density: "",
                type: "самоклеящаяся",
                quality: "",
                color: "белая",
                prices: {
                    upTo1: "1780",
                    upTo5: "1680",
                    upTo20: "1450",
                    upTo100: "1185",
                    over100: "1080",
                },
            },
            {
                value: "6",
                material: "Пленка",
                density: "",
                type: "самоклеящаяся",
                quality: "",
                color: "прозрачная",
                prices: {
                    upTo1: "1780",
                    upTo5: "1680",
                    upTo20: "1450",
                    upTo100: "1185",
                    over100: "1080",
                },
            },
        ],
    },
    {
        title: "Дополнительные работы",
        options: [
            {
                value: "1",
                title: "Подрезка края по изображению (бумага, баннер, пленка, холст)",
                price: "12",
                forMaterial: ["Бумага", "Фотобумага", "Баннер", "Пленка", "Холст"],
                titleExceptions: [],
                typeExceptions: [],
            },
            {
                value: "2",
                title: "Подрезка края по изображению (пластик)",
                price: "50",
                forMaterial: ["ПВХ 3мм", "ПЭТ 1мм", "Акрил 3мм", "Двухслойный пластик"],
                titleExceptions: [],
                typeExceptions: [],
            },
            {
                value: "3",
                title: "Проклейка по периметру",
                price: "50",
                forMaterial: ["Баннер", "Баннерная сетка"],
                titleExceptions: [],
                typeExceptions: ["для роллерных стендов"],
            },
            {
                value: "4",
                title: "Установка люверсов",
                price: "11",
                forMaterial: ["Баннер", "Баннерная сетка"],
                titleExceptions: [],
                typeExceptions: ["для роллерных стендов"],
            },
            {
                value: "5",
                title: "Плоттерная резка",
                price: "330",
                forMaterial: ["Пленка"],
                titleExceptions: [],
                typeExceptions: ["перфорированная"],
            },
            {
                value: "6",
                title: "Ламинация",
                price: "330",
                forMaterial: ["Бумага", "Фотобумага", "Пленка"],
                titleExceptions: ["Планшетная УФ-печать", "Рулонная УФ-печать"],
                typeExceptions: ["перфорированная"],
            },
            {
                value: "7",
                title: "Ламинация напольная",
                price: "620",
                forMaterial: ["Пленка"],
                titleExceptions: ["Планшетная УФ-печать", "Рулонная УФ-печать"],
                typeExceptions: ["перфорированная"],
            },
        ],
    },
]
